2019-05-11 10:52:25 method: api.advanced.data_check_cookies.utils.HttpUtils.get(HttpUtils.java:78) - [ ERROR ]----工具类get请求调用出现异常Connect to 192.168.0.99:9000 [/192.168.0.99] failed: Connection timed out: connect
2019-05-11 10:52:47 method: api.advanced.data_check_cookies.utils.HttpUtils.get(HttpUtils.java:78) - [ ERROR ]----工具类get请求调用出现异常Connect to 192.168.0.99:9000 [/192.168.0.99] failed: Connection timed out: connect
2019-05-11 10:54:09 method: api.advanced.data_check_cookies.utils.HttpUtils.get(HttpUtils.java:78) - [ ERROR ]----工具类get请求调用出现异常Connect to localhost:80 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect
2019-05-11 10:54:12 method: api.advanced.data_check_cookies.utils.HttpUtils.get(HttpUtils.java:78) - [ ERROR ]----工具类get请求调用出现异常Connect to localhost:80 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect
2019-05-11 10:54:14 method: api.advanced.data_check_cookies.utils.HttpUtils.get(HttpUtils.java:78) - [ ERROR ]----工具类get请求调用出现异常Connect to localhost:80 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect
2019-05-11 10:54:16 method: api.advanced.data_check_cookies.utils.HttpUtils.get(HttpUtils.java:78) - [ ERROR ]----工具类get请求调用出现异常Connect to localhost:80 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect
2019-05-11 10:54:18 method: api.advanced.data_check_cookies.utils.HttpUtils.get(HttpUtils.java:78) - [ ERROR ]----工具类get请求调用出现异常Connect to localhost:80 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect
2019-05-11 10:54:20 method: api.advanced.data_check_cookies.utils.HttpUtils.get(HttpUtils.java:78) - [ ERROR ]----工具类get请求调用出现异常Connect to localhost:80 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect
2019-05-11 10:54:22 method: api.advanced.data_check_cookies.utils.HttpUtils.post(HttpUtils.java:187) - [ ERROR ]----工具类post请求调用出现异常Connect to localhost:80 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: Connection refused: connect
